name: deploy-1
on:
    push:
        branches: ["deploy"]

jobs:
    lets-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.Host}}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: | 
                    cd /home/ubuntu/my-app
                    git pull
                    docker compose up -d --build

