name: my second pipline
on: 
    push:
        branches: ["develop"]

env:
    APP_NAME: "mygreatapp"
    APP_ENV: "staging"
    SECRET: ${{ secrets.SUPER_SECRET }}

jobs: 
   print-vars:
     runs-on: ubuntu-latest
     steps: 
       - name: show Congig
         run: echo "Develop $APP_NAME TO $APP_ENV enviroment"

       - name: print secret
         run: echo " il segreto Ã¨:... $SECRET"
